name: build TesLight Update Packaging Tool
on:
  push:
    branches: ["main", "releases/**", "feat/DevOps_Auto_build_for_Update_Packages"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: g++ build
        shell: cmd
        working-directory: update-package-tool
        run: |
          mkdir build
          g++ -g src\*.cpp -o build\tupt.exe

      - name: publish TesLight Update Packaging Tool
        uses: actions/upload-artifact@v3
        with:
          name: TesLight_Update_Packaging_Tool
          path: build\tupt.exe
