name: build TesLight Update Packaging Tool and TUP file
on:
  push:
    branches: ["main", "releases/**", "feat/DevOps_Auto_build_for_Update_Packages"]
    tags: ["v*", "v**", "v.*", "v.**" ]
  pull_request:
    branches: ["main", "releases/**"]
  workflow_dispatch:
  workflow_call:
jobs:
  build_update_tool_for_different_os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    # prevent stuck jobs
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full checkout is needed not just the commited code
          fetch-depth: 0

      - name: Update Tool Build
        uses: ./.github/actions/update-tool-build

  generate_tup_file:
    needs: [build_update_tool_for_different_os]
    runs-on: ubuntu-latest
    # prevent stuck jobs
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full checkout is needed not just the commited code
          fetch-depth: 0

      - name: PlatformIO Build
        uses: ./.github/actions/platformio-build

      - name: UI Build
        uses: ./.github/actions/ui-build

      - name: Download artifact - PlatformIO Build
        uses: actions/download-artifact@v3
        with:
          name: PlatformIO-build
          path: ./update-package-tool/build/tup/src

      - name: Download artifact - UI Build
        uses: actions/download-artifact@v3
        with:
          name: UI-build
          path: ./update-package-tool/build/tup/src

      - name: Download artifact - TesLight_Update_Packaging_Tool
        uses: actions/download-artifact@v3
        with:
          name: TesLight_Update_Packaging_Tool_for_${{ runner.os }}
          path: update-package-tool/build

      - name: File permissions
        if: startsWith(${{ runner.os }},'ubuntu') || startsWith(${{ runner.os }},'macOS')
        shell: bash
        run: chmod +x ./update-package-tool/build/tupt_for_*.exe

      - name: tup build
        shell: bash
        run: |
          mkdir -p ./update-package-tool/build/tup/build
          ./update-package-tool/build/tupt_for_${{ runner.os }}.exe ./update-package-tool/build/tup/build/update_${GITHUB_SHA::6}.tup ./update-package-tool/build/tup/src

      - name: publish TesLight Update Package File
        uses: actions/upload-artifact@v3
        with:
          name: TesLight_Update_Package
          path: ./update-package-tool/build/tup/build/update_${GITHUB_SHA::6}.tup
